### PR TITLE
Fixed Appveyor build issue [PHP_SECURITY_FLAGS]

### PR DESCRIPTION
**Pull request by sergeyklay**
Refs: https://github.com/tideways/php-profiler-extension/pull/12

### CODE REVIEW

**Comment by sergeyklay** [comment]
@beberlei Could you please take a look.
I hope this will fix Appveyor build issue.

**Comment by Vincent--** [comment]
Hi,

Any reason I'm in cc?

**Comment by sergeyklay** [comment]
I'm sorry 😐 

Cc by mistake

**Comment by sergeyklay** [comment]
@beberlei 

I would like to draw your attention that despite the fact that I fixed the AppVeyor build, the extension does not compile as NTS at all. For example note that despite the fact that you specify explicitly `RELEASE_FOLDER` as `Release` it always stored in `Release_TS`.

I spent a lot of time to figure it out. It was not easy, given the fact that I have no Windows machine.

Nevertheless, I've managed how to do for [our extension](https://github.com/phalcon/php-zephir-parser). You [are free to borrow any part of it](https://github.com/phalcon/php-zephir-parser/blob/development/.appveyor.yml).

Best regards,

**Comment by sergeyklay** [comment]
screenshot at mar 31 17-39-12

**Comment by beberlei** [comment]
@sergeyklay thank you :-) The windows build is still in alpha, certainly because i have never worked on a windows extension before and all this build related stuff is very hard to get into.

**Pull request merged**
