### PR TITLE
Update version for 4.1.1 release

### PR DESCRIPTION
**Pull request by adambaratz**

### CODE REVIEW

**Comment by sergeyklay** [comment]
4.1.2 in master branch

**Comment by adambaratz** [comment]
Ah, that's true. But this value is set incorrectly in the tagged release. Is there a way to fix that?

**Comment by sergeyklay** [comment]
As I can see the 4.1.1 and 4.1.2 already released. What do you want to update?

**Comment by adambaratz** [comment]
Looks like the code changed since I posted this. Nothing to worry about then. Thanks!

**Pull request closed without merging**
